### ISSUE TITLE
Operation timed out

### ISSUE THREAD

**Issue by ljacho** [kevinmershon/pynia#1]
I have just tried your module and I am getting 
`(110, u'Operation timed out')` in `read_bytes = self.handle.interruptRead(0x81, 64, 25)`.

Am I doing something wrong?

**Comment by kevinmershon** [comment]
TBQH I haven't touched this project in awhile. My best guess is that you need to make sure the USB serial device in `/dev` corresponding to your NIA matches what the source expects, and that the backend piece is either running as root or your current user has access to read from the device.

**Comment by ljacho** [comment]
thank you for your quick response ;) it is working now and I didnt anything.. I think that my NIA OCZ is kind of buggy
